l91_sulu_form.tests:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\ListController
    prefix: l91/form
    name_prefix: l91_sulu_form.

l91_sulu_form.dynamic.list:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\DynamicListController
    prefix: l91/form
    name_prefix: l91_sulu_form.

l91.sulu.form.forms:
    type: rest
    resource: L91\Sulu\Bundle\FormBundle\Controller\FormController
    prefix: l91
    name_prefix: l91_sulu_form.
